### ISSUE TITLE
Docs: command line in Readme

### ISSUE THREAD

**Issue by veecle-sohyeon** [veecle/veecle-pxros#6]
Minor things:

Under Installation,
Install tricore-probe via `cargo install --git https://github.com/veecle/tricore-probe`. Make sure the listed requirements are installed.

I got this error (I guess it needs to be `cargo install --git https://github.com/veecle/tricore-probe tricore-probe`)
<img width="893" alt="image" src="https://github.com/veecle/veecle-pxros/assets/125027504/363fc654-90c5-45da-9309-b8b11e4b5f35">

**Comment by arctic-alpaca** [comment]
Thanks for the report @veecle-sohyeon!
